[package]
name = "AgentArena"
version = "0.1.0"
edition = "2024.beta"

[addresses]
agent_arena = "0x0"

[dependencies]
One = { git = "https://github.com/one-chain-labs/onechain.git", subdir = "crates/sui-framework/packages/one-framework", rev = "v1.1.1", override = true }

[dev-addresses]
agent_arena = "0x0"
